[[main]]
  identifier = "dropdown"
  name = "Dropdown"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  id = "github"
  parent = "dropdown"
  name = "Github"
  url = "https://github.com/yhseokshow"
