email = "user@domain.tld"
facebook = "yourfacebookusername"
github = "yourgithubusername"
gitlab = "yourgitlabusername"
linkedin = "yourlinkedinusername"
stackoverflow = "yourstackoverflowuserid"
twitter = "yourtwitterusername"
instagram = "yourinstagramusername"
quora = "yourquorausername"
tumblr = "yourtumblrusername"
reddit = "yourredditusername"
telegram = "yourtelegramusername"
dockerhub = "yourdockerhubusername"
bitbucket = "yourbitbucketworkspaceid"
medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).

#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#qq = "yourqqnumber"
#lastfm = "yourlastfmusername"
#bilibili = "yourbilibiliuserid"
