[build]
publish = "dist"
command = "hugo --minify -D -b=https://yhseok-dev-blog.netlify.app/"

[context.production.environment]
HUGO_VERSION = "0.85.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.develop.environment]
HUGO_VERSION = "0.85.0"
HUGO_ENABLEGITINFO = "true"
