[build]
publish = "dist"
command = "hugo --minify --theme=repo -b=https://hugo-theme-bootstrap.netlify.app/"

[context.production.environment]
HUGO_VERSION = "0.85.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.develop.environment]
HUGO_VERSION = "0.85.0"
HUGO_ENABLEGITINFO = "true"
